// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACMzJrGzeCSP4W2Aqcy3aCoWJVydEJyWQ',
    appId: '1:481351842886:web:94e1034ea8575d215d5e47',
    messagingSenderId: '481351842886',
    projectId: 'thepetshop-b9bd8',
    authDomain: 'thepetshop-b9bd8.firebaseapp.com',
    storageBucket: 'thepetshop-b9bd8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJH2PSxQczp1Is6e1TjdFh7v-thUsead4',
    appId: '1:481351842886:android:7c149735afbfd9d05d5e47',
    messagingSenderId: '481351842886',
    projectId: 'thepetshop-b9bd8',
    storageBucket: 'thepetshop-b9bd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn6loxTmnZ14zHliQZ-0IAF2RdjGSIDoM',
    appId: '1:481351842886:ios:b185b564061eaee85d5e47',
    messagingSenderId: '481351842886',
    projectId: 'thepetshop-b9bd8',
    storageBucket: 'thepetshop-b9bd8.appspot.com',
    iosClientId: '481351842886-slua72gfqcq16ekco36hkbclprpsrlqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.petShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn6loxTmnZ14zHliQZ-0IAF2RdjGSIDoM',
    appId: '1:481351842886:ios:b185b564061eaee85d5e47',
    messagingSenderId: '481351842886',
    projectId: 'thepetshop-b9bd8',
    storageBucket: 'thepetshop-b9bd8.appspot.com',
    iosClientId: '481351842886-slua72gfqcq16ekco36hkbclprpsrlqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.petShop',
  );
}
